name: HotPotato
main: cn.lanink.hotpotato.HotPotato
version: "1.0.4-SNAPSHOT"
api:
  - 1.0.0
load: POSTWORLD
author: "LT_Name"
depend:
  - "MemoriesOfTime-GameCore"

permissions:
  HotPotato.command.user:
    default: true
  HotPotato.command.admin:
    default: op